name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          ./bashbrew.sh --version > /dev/null
          bin/bashbrew --version
      - name: Smoke Test
        run: |
          image='https://github.com/docker-library/official-images/raw/master/library/hello-world'
          bin/bashbrew list "$image"
          bin/bashbrew list --uniq "$image"
          bin/bashbrew cat "$image"
          bin/bashbrew from --uniq "$image"
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go Test
        run: |
          docker build --pull --file Dockerfile.test --tag test .
          docker run --rm test cat coverage.out > coverage.out
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
  dockerfile:
    name: Test Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: |
          docker build --pull .
  dockerfile-release:
    name: Test Dockerfile.release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile.release
        run: |
          docker build --pull --file Dockerfile.release .
